import React from "react";
import ReactDOM from "react-dom";

const fName = "Cristian";
const lName = "Villalba";
const luckynumber = "7";

ReactDOM.render(
  <div>
    <h1>JavaScript expressions in JSX!</h1>
    <p>
      The Curly Braces {"{}"} allows us to add JavaScript Expressions <br />
      but we can not write JavaScript Statements.
    </p>
    <p>Here are some exaples:</p>
    {/* basic use of JS variables */}
    <p>
      Variables: {fName} {lName}
    </p>
    {/* Concatenation */}
    <p>Concatenation: {fName + " " + lName}</p>
    {/* Template Literal */}
    <p>Template Literal: {`${fName} ${lName}`} </p>
    {/* variable injected */}
    <p>Your Lucky Number variable is {luckynumber}</p>
    {/* maths using JS in our HTML in our JS  */}
    <p>Your Lucky Number generated by JS Maths is {3 + 4}</p>
  </div>,
  document.getElementById("root")
);
